### PR TITLE
Bugs corrections and code refactor

### PR DESCRIPTION
**Pull request by juanarbol**

### CODE REVIEW

**Comment by lunzhang** [comment]
Hi, thanks for contributing!  Everything works except the run scripts.  I use a windows machine so the two watch scripts don't run in parallel.  Maybe we could add this [concurrently](https://www.npmjs.com/package/concurrently) so then the scripts run in parallel in all platforms.

**Comment by juanarbol** [comment]
Oh, on OS X and Linux won't work the scripts, I highly recommend you use Linux [subsystem](https://msdn.microsoft.com/en-us/commandline/wsl/about) in your machine, after all, this game will be deployed on a Linux server

**Comment by juanarbol** [comment]
That's it

**Comment by lunzhang** [comment]
merged.  thanks for the changes!

**Comment by juanarbol** [comment]
I love this!

**Comment by lunzhang** [comment]
Hi, sorry I overlooked this but it looks like dev script is ran with webpack instead of webpack-dev-server, which doesn't cause browser refresh on change. and concurrently isn't required for the start script, since npm run build would end.

**Comment by juanarbol** [comment]
Ok, I'll create another pull request, just give me some time

**Pull request merged**
